# -*- coding: utf-8 -*-
"""1차시험-엄선민.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JOCiJ4oDet0GAGSF4t0q4lCY57C7WzBu
"""

#문1 나의이름은: 홍길동 나의 나이는: 100 나의 성별은 : 남 나의 좌우명은: 열심히 살자
name=input("나의 이름은 ")
age=int(input("나의 나이는 "))
age1= age+1
gender=input("나의 성별은 ")
motto=input("나의 좌우명은 ")

print("========================")
print("나는 ", name, "이고, 내 나이는 ", age, "세, 내년 나이는 ", age1, "세가 될 예정이고, ",1
      "나는 ", gender,", 나는 ", motto, "!가 내 좌우명!" )

#문2 55부터 100까지 2씩 점프한 값을 출력
for i in range(55, 101, 2):
  print(i)

#문3 홍길동 김길동 송길동 박길동 정길동 (계속 입력) x 또는 X를 입력 받으면 입력을 멈춤. 
#다음과 같이 출력 : 첫번째 선수는 홍길동, 세번째 선수는 송길동
name=[]
while True:
  data= input("이름 : ")
  if data == "x" or data == "X":
    print("입력 멈춤")
    break
  else:
    name.append(data)
    
print("첫번째 선수는 ", name[0], ", 세번째 선수는 ", name[2] )

