# -*- coding: utf-8 -*-
"""파이썬제어문.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wtOneHGdlOt8ZrzItx7Yle0HEOCQmRqX
"""

food = input('먹고 싶은 음식을 입력하세요.>> ')
print('당신이 입력한 먹고싶은 음식은 ', food)

if food == '우동':
  print('우산을 들고간다')
  print('돈')
  print('우동집으로')
elif food == '짜장면':
  print('중국집')
elif food == '라면':
  print('분식집')
else: #else 뒤에는 조건을 쓰지 않는다. if 뒤에는 조건 반드시 붙는다.
  print('집') #pass

start = 0
while start < 10: #Ture라면 반복해라
  print(start, '> 내가 반복') 
  start =start + 1
#정해진 횟수만큼 반복 \ 시작값, 끝값 증감식. count는 0부터 시작하는 경우가 많다.

for _ in range(0,10): #0~9까지의 범위 ; 증감식이 없음 = 디폴트로 +1인걸로 기본값
  print('나도 반복')

for x in range(10):
  print(x, '> 뿅')

time = int(input("현재시각>>"))
if time < 11:
  print ("good morning")
elif time<15:
  print("good afternoon")
elif time <20:
  print("good evening")
else:
  print("good night")
#현재시각 11시
#11시 전이면 goodmorning; 15시전이면 aft. 20 even. 위 조건 아니면 굿나잇

month = int(input("이번 달>>"))
#for month in range(0,13)
print(month)
if 2<month<6:
  print("봄")
elif 5<month<9:
  print("여름")
elif 8<month<12:
  print("가을")
else:
  print("겨울")
#이번달은 1월
#345=봄/6~8/9~11/ 다른달은ㅇ 겨울